### PR TITLE
Property tests

### PR DESCRIPTION
**Pull request by rustkas**
- Add property based tests.
- Fix GNUmakefile doc generation target.

### CODE REVIEW

**Comment by mworrell** [comment]
One of the property tests seem to fail.

Didn't look into it yet, might be a problem with the code that your test is uncovering.

**Comment by rustkas** [comment]
Yes. Unfortunately it is. It is analogous `test_deadline`. I will try to fix it.

**Comment by mworrell** [comment]
Thanks!

Do you think the deadline test is unstable, or that there is an issue in the buffalo code?

**Comment by mworrell** [comment]
Really good work, also on all the other repos you are working on.

**Comment by rustkas** [comment]
> Thanks!
> 
> Do you think the deadline test is unstable, or that there is an issue in the buffalo code?

I think that it is necessary to carefully analyze the work of this test (`test_deadline()`). It was very strange that the test worked on one of my computers, but did not work in an isolated environment. I think that due to the use of the `ets`-table (probably) or some other peculiarities of the delay calculation, unexpected behavior occurs.

`test/buffalo_test.erl`
```
> 92   ok = dont_receive(trunc(0.5*Unit)),
       buffalo:queue(Key, MFA, #{ timeout => Unit }),
       % We are now at 4.7 x initial unit
       % The deadline (at 5x) should trigger soon.
       Msg = do_receive(Msg, trunc(0.4*Unit)),
       % And the queue should be emptied.
> 98   ok = dont_receive(trunc(1.2*Unit)).
```

Erroneous results are obtained in lines 92, 98.

**Comment by mworrell** [comment]
Released version 2.1.0

**Pull request merged**
